---
- hosts: localhost
  vars:

  tasks:

  - debug: { msg: "{{ ansible_architecture }} " }
  - debug: { msg: "{{ ansible_os_family }} " }

  - name: Update APT cache
    apt:
      update_cache: yes
    become: yes

  - name: Prepare AP (https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md)
    block:
      - name: Install dnsmasq and hostapd without starting them
        apt:
          name: "{{ packages }}"
        vars:
          packages:
            - dnsmasq 
            - hostapd
        environment:
          RUNLEVEL: 1
      - name: Update /etc/dhcpd.conf
        blockinfile:
          path: /etc/dhcpcd.conf
          insertafter: EOF
          block: |
            interface wlan0
              static ip_address=192.168.4.1/24
              nohook wpa_supplicant
      - name: Restart service dhcpcd
        service:
          name: dhcpcd
          state: started
          enabled: yes
    become: yes


  - name: Install InfluxDB and Telegraph on x86_64
    block:
      - name: Download and install InfluxDB from .deb
        apt:
          deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.7.1_amd64.deb
      - name: Download and install Telegraph from .deb
        apt:
          deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.9.0-1_amd64.deb
    when: ansible_architecture == "x86_64"
    tags:
      - influx
    become: yes

  - name: InfluxDB and Telegraph on ARM
    block:
      - name: Install Telegraph for ARM from tarball
        unarchive:
          src: https://dl.influxdata.com/telegraf/releases/telegraf-1.9.0_linux_armhf.tar.gz
          dest: /
          remote_src: yes
    when: ansible_architecture == "ARM"
    become: yes


  - name: Install Mosquitto MQTT broker (https://mosquitto.org)
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - mosquitto
        - mosquitto-clients
    become: yes

  - name: Install bluetooth
    apt:
      name: bluetooth
    become: yes

  - name: Install oFono (https://01.org/ofono)
    apt:
      name: ofono
    become: yes

  - name: indiana-bluez | Create Unit file
    template: src=indiana-bluez.service.j2 dest=/lib/systemd/system/indiana-bluez.service mode=644
    notify:
      - reload systemctl
    become: yes

  - name: indiana-bluez | Start indiana-bluez
    service: name=indiana-bluez.service state=started enabled=yes
    become: yes
