---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:

  tasks:

  - debug: { msg: "{{ ansible_architecture }}" }
  - debug: { msg: "{{ ansible_os_family }}" }

  - name: Update APT cache
    apt:
      update_cache: yes

  - name: Install requirements for pydbus
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - libgirepository1.0-dev 
        - libcairo2-dev

  - name: Clone https://github.com/ejojmjn/indiana-bluez.git
    git:
      repo: https://github.com/ejojmjn/indiana-bluez.git
      dest: indiana-bluez
  - name: Install requirements for indiana-bluez
    pip:
      requirements: /home/pi/indiana-bluez/requirements.txt
  - name: Create unit file for indiana-bluez
    template: 
      src: indiana-bluez.service.j2
      dest: /lib/systemd/system/indiana-bluez.service
      mode: 644
    notify:
      - reload systemctl
  - name: Start indiana-bluez service
    service: 
      name: indiana-bluez
      state: started
      enabled: yes
