---
- hosts: localhost
  connection: local
  become: yes
  vars:
    ssid: "ACT"
  tasks:

  - debug: { msg: "{{ ansible_architecture }} " }
  - debug: { msg: "{{ ansible_os_family }} " }

#  - name: Update APT cache
#    apt:
#      update_cache: yes
#    become: yes

  - name: Prepare AP (https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md)
    block:
      - name: Install dnsmasq and hostapd without starting them
        apt:
          name: "{{ packages }}"
        vars:
          packages:
            - dnsmasq 
            - hostapd
        environment:
          RUNLEVEL: 1
      - name: Update /etc/dhcpd.conf
        blockinfile:
          path: /etc/dhcpcd.conf
          insertafter: EOF
          block: |
            interface wlan0
                static ip_address=192.168.42.1/24
                nohook wpa_supplicant
      - name: Restart service dhcpcd
        service:
          name: dhcpcd
          state: started
          enabled: yes
